// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveCollection is the `removeCollection` instruction.
type RemoveCollection struct {

	// [0] = [] candyMachine
	//
	// [1] = [SIGNER] authority
	//
	// [2] = [WRITE] collectionPda
	//
	// [3] = [] metadata
	//
	// [4] = [] mint
	//
	// [5] = [WRITE] collectionAuthorityRecord
	//
	// [6] = [] tokenMetadataProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveCollectionInstructionBuilder creates a new `RemoveCollection` instruction builder.
func NewRemoveCollectionInstructionBuilder() *RemoveCollection {
	nd := &RemoveCollection{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *RemoveCollection) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(candyMachine)
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *RemoveCollection) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *RemoveCollection) SetAuthorityAccount(authority ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *RemoveCollection) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCollectionPdaAccount sets the "collectionPda" account.
func (inst *RemoveCollection) SetCollectionPdaAccount(collectionPda ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(collectionPda).WRITE()
	return inst
}

// GetCollectionPdaAccount gets the "collectionPda" account.
func (inst *RemoveCollection) GetCollectionPdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMetadataAccount sets the "metadata" account.
func (inst *RemoveCollection) SetMetadataAccount(metadata ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(metadata)
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *RemoveCollection) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMintAccount sets the "mint" account.
func (inst *RemoveCollection) SetMintAccount(mint ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *RemoveCollection) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetCollectionAuthorityRecordAccount sets the "collectionAuthorityRecord" account.
func (inst *RemoveCollection) SetCollectionAuthorityRecordAccount(collectionAuthorityRecord ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(collectionAuthorityRecord).WRITE()
	return inst
}

// GetCollectionAuthorityRecordAccount gets the "collectionAuthorityRecord" account.
func (inst *RemoveCollection) GetCollectionAuthorityRecordAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenMetadataProgramAccount sets the "tokenMetadataProgram" account.
func (inst *RemoveCollection) SetTokenMetadataProgramAccount(tokenMetadataProgram ag_solanago.PublicKey) *RemoveCollection {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenMetadataProgram)
	return inst
}

// GetTokenMetadataProgramAccount gets the "tokenMetadataProgram" account.
func (inst *RemoveCollection) GetTokenMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst RemoveCollection) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveCollection,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveCollection) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveCollection) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CollectionPda is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.CollectionAuthorityRecord is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenMetadataProgram is not set")
		}
	}
	return nil
}

func (inst *RemoveCollection) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveCollection")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             candyMachine", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            collectionPda", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                 metadata", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("                     mint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("collectionAuthorityRecord", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     tokenMetadataProgram", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj RemoveCollection) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *RemoveCollection) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewRemoveCollectionInstruction declares a new RemoveCollection instruction with the provided parameters and accounts.
func NewRemoveCollectionInstruction(
	// Accounts:
	candyMachine ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	collectionPda ag_solanago.PublicKey,
	metadata ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	collectionAuthorityRecord ag_solanago.PublicKey,
	tokenMetadataProgram ag_solanago.PublicKey) *RemoveCollection {
	return NewRemoveCollectionInstructionBuilder().
		SetCandyMachineAccount(candyMachine).
		SetAuthorityAccount(authority).
		SetCollectionPdaAccount(collectionPda).
		SetMetadataAccount(metadata).
		SetMintAccount(mint).
		SetCollectionAuthorityRecordAccount(collectionAuthorityRecord).
		SetTokenMetadataProgramAccount(tokenMetadataProgram)
}
