// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetCollection is the `setCollection` instruction.
type SetCollection struct {

	// [0] = [] candyMachine
	//
	// [1] = [SIGNER] authority
	//
	// [2] = [WRITE] collectionPda
	//
	// [3] = [SIGNER] payer
	//
	// [4] = [] systemProgram
	//
	// [5] = [] rent
	//
	// [6] = [] metadata
	//
	// [7] = [] mint
	//
	// [8] = [] edition
	//
	// [9] = [WRITE] collectionAuthorityRecord
	//
	// [10] = [] tokenMetadataProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetCollectionInstructionBuilder creates a new `SetCollection` instruction builder.
func NewSetCollectionInstructionBuilder() *SetCollection {
	nd := &SetCollection{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *SetCollection) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(candyMachine)
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *SetCollection) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *SetCollection) SetAuthorityAccount(authority ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *SetCollection) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetCollectionPdaAccount sets the "collectionPda" account.
func (inst *SetCollection) SetCollectionPdaAccount(collectionPda ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(collectionPda).WRITE()
	return inst
}

// GetCollectionPdaAccount gets the "collectionPda" account.
func (inst *SetCollection) GetCollectionPdaAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayerAccount sets the "payer" account.
func (inst *SetCollection) SetPayerAccount(payer ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *SetCollection) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *SetCollection) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *SetCollection) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetRentAccount sets the "rent" account.
func (inst *SetCollection) SetRentAccount(rent ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *SetCollection) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMetadataAccount sets the "metadata" account.
func (inst *SetCollection) SetMetadataAccount(metadata ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(metadata)
	return inst
}

// GetMetadataAccount gets the "metadata" account.
func (inst *SetCollection) GetMetadataAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMintAccount sets the "mint" account.
func (inst *SetCollection) SetMintAccount(mint ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *SetCollection) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetEditionAccount sets the "edition" account.
func (inst *SetCollection) SetEditionAccount(edition ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(edition)
	return inst
}

// GetEditionAccount gets the "edition" account.
func (inst *SetCollection) GetEditionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetCollectionAuthorityRecordAccount sets the "collectionAuthorityRecord" account.
func (inst *SetCollection) SetCollectionAuthorityRecordAccount(collectionAuthorityRecord ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(collectionAuthorityRecord).WRITE()
	return inst
}

// GetCollectionAuthorityRecordAccount gets the "collectionAuthorityRecord" account.
func (inst *SetCollection) GetCollectionAuthorityRecordAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenMetadataProgramAccount sets the "tokenMetadataProgram" account.
func (inst *SetCollection) SetTokenMetadataProgramAccount(tokenMetadataProgram ag_solanago.PublicKey) *SetCollection {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenMetadataProgram)
	return inst
}

// GetTokenMetadataProgramAccount gets the "tokenMetadataProgram" account.
func (inst *SetCollection) GetTokenMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst SetCollection) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetCollection,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetCollection) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetCollection) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.CollectionPda is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Metadata is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Edition is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.CollectionAuthorityRecord is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenMetadataProgram is not set")
		}
	}
	return nil
}

func (inst *SetCollection) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetCollection")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             candyMachine", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("            collectionPda", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("                    payer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("            systemProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                     rent", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("                 metadata", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("                     mint", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("                  edition", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("collectionAuthorityRecord", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("     tokenMetadataProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj SetCollection) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *SetCollection) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewSetCollectionInstruction declares a new SetCollection instruction with the provided parameters and accounts.
func NewSetCollectionInstruction(
	// Accounts:
	candyMachine ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	collectionPda ag_solanago.PublicKey,
	payer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	metadata ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	edition ag_solanago.PublicKey,
	collectionAuthorityRecord ag_solanago.PublicKey,
	tokenMetadataProgram ag_solanago.PublicKey) *SetCollection {
	return NewSetCollectionInstructionBuilder().
		SetCandyMachineAccount(candyMachine).
		SetAuthorityAccount(authority).
		SetCollectionPdaAccount(collectionPda).
		SetPayerAccount(payer).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent).
		SetMetadataAccount(metadata).
		SetMintAccount(mint).
		SetEditionAccount(edition).
		SetCollectionAuthorityRecordAccount(collectionAuthorityRecord).
		SetTokenMetadataProgramAccount(tokenMetadataProgram)
}
